feat. add softdepend protocolibs
MineWeb/ServerBridge pull request #12
Opened 2020-01-08 19:46 UTC by nivcoo

2020-01-08 19:47 UTC, nivcoo commented
Alors oui beaucoup de commit, mais je me rendais compté au fur et à mesure que ma branch était pas a jour ahah

2020-01-09 09:54 UTC, Eywek commented on build.gradle
> +version = '3.0.3'
Faut aussi changer la version dans `.github/workflows/gradle.yml` même si pour l'instant ça marche pas

2020-01-09 10:39 UTC, vmarchaud requested changes

2020-01-09 10:39 UTC, vmarchaud commented on src/main/java/fr/vmarchaud/mineweb/bukkit/BukkitCore.java
> +import net.md_5.bungee.api.ChatColor;
Pretty sure that the wrong import :)

2020-01-09 11:22 UTC, nivcoo commented on build.gradle
> +version = '3.0.3'
Ok je le fais ce soir

2020-01-09 11:22 UTC, nivcoo commented on src/main/java/fr/vmarchaud/mineweb/bukkit/BukkitCore.java
> +import net.md_5.bungee.api.ChatColor;
Yes

2020-01-09 18:20 UTC, nivcoo commented on src/main/java/fr/vmarchaud/mineweb/bukkit/BukkitCore.java
> +import net.md_5.bungee.api.ChatColor;
Done

2020-01-09 18:20 UTC, nivcoo commented on build.gradle
> +version = '3.0.3'
C'est bon

2020-01-09 18:23 UTC, vmarchaud approved these changes

2020-01-10 13:48 UTC, Eywek commented on build.gradle
> +version = '3.0.3'
Je vois pas le change

2020-01-10 21:11 UTC, nivcoo commented on build.gradle
> +version = '3.0.3'
Euh, pourtant je l'ai bien changé, et tu suggere quoi pour faire que la doc recup la derniere version du pl ?

2020-01-10 21:13 UTC, nivcoo commented on build.gradle
> +version = '3.0.3'
Voila, je l'ai fait directement via le site, il doit être ignoré via le cmd ou jsp

2020-01-16 23:19 UTC, Shyrogan commented
Seems good

2020-01-17 04:40 UTC, MaximeMichaud commented
> Seems good

Seems good :) @Eywek

2020-01-17 04:41 UTC, MaximeMichaud approved these changes

2020-01-17 08:07 UTC, merged